import("//flutter/common/config.gni")

source_set("patch_cache") {
  sources = [
    "patch_cache.cc",
    "patch_cache.h",
    "patch_mapping.cc",
    "patch_mapping.h",
  ]

  deps = [
    "//flutter/fml",
    "//flutter/runtime:libdart",
    "//flutter/shell/common/shorebird:updater",
  ]

  if (is_ios || is_mac) {
    deps += [ "$dart_src/runtime/bin:shared_object_loaders" ]
  } else {
    deps += [ "$dart_src/runtime/bin:elf_loader" ]
  }
}
