import("//flutter/common/config.gni")

source_set("patch_cache") {
  sources = [
    "patch_cache.cc",
    "patch_cache.h",
    "patch_mapping.cc",
    "patch_mapping.h",
  ]

  deps = [
    "$dart_src/runtime/bin:libdart_builtin",
    "$dart_src/runtime/bin:shared_object_loaders",
    "//flutter/fml",
    "//flutter/runtime:libdart",
    "//flutter/shell/common/shorebird:updater",
  ]
}
