name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
      - tonycloud/dev

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: 🧪 Test

    env:
      FLUTTER_STORAGE_BASE_URL: https://download.shorebird.dev

    defaults:
      run:
        shell: bash

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all branches and tags to ensure that Flutter can determine its version
          fetch-depth: 0

      - name: 🏷️ Fetch Flutter release tag
        run: git fetch --no-tags https://github.com/flutter/flutter.git +refs/tags/3.47.0:refs/tags/3.47.0

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: 📦 Install Dependencies
        run: |
          ./bin/flutter pub get -C ./dev/bots
          ./bin/flutter pub get -C ./dev/tools

      - name: 🧪 Run Tests
        env:
          SHARD: tool_tests
          SUBSHARD: general
        run: dart --enable-asserts ./dev/bots/test.dart
